exclude: []

permalink: /blog/:year/:month/:title

owner_link: http://kenhowardpdx.com

url: http://kenhowardpdx.com

domain: kenhowardpdx.com

title: A Blog About Website Design and Front-End Development

markdown: redcarpet
